// <auto-generated />
namespace Ban_Sach_Online.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FixGioHang1to1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixGioHang1to1));
        
        string IMigrationMetadata.Id
        {
            get { return "202511050208535_FixGioHang1to1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
