// <auto-generated />
namespace Ban_Sach_Online.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SachDaBan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SachDaBan));
        
        string IMigrationMetadata.Id
        {
            get { return "202511110431243_SachDaBan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
